// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhpEIt_jrLH7jGkZtgrZGoS5Sq0Uh8s8M',
    appId: '1:27553399266:android:cf821653df59adc5f879bb',
    messagingSenderId: '27553399266',
    projectId: 'aquatrack-5469f',
    databaseURL: 'https://aquatrack-5469f-default-rtdb.firebaseio.com',
    storageBucket: 'aquatrack-5469f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnvEWGlWJqI8FreQtRa1r0WAzLBRRnZsA',
    appId: '1:27553399266:ios:53da0dfb76abf29cf879bb',
    messagingSenderId: '27553399266',
    projectId: 'aquatrack-5469f',
    databaseURL: 'https://aquatrack-5469f-default-rtdb.firebaseio.com',
    storageBucket: 'aquatrack-5469f.firebasestorage.app',
    iosClientId: '27553399266-l5l4skdng4vkp0j30qqu5dtm90jjj6p5.apps.googleusercontent.com',
    iosBundleId: 'com.sfac.aquatrack',
  );
}
